arm:
  type: ur10
sensors:
# over agv 1
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.5]
      rpy: [0, 'pi/2', 0]
# over agv 2
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [0.3, -3.15, 1.5]
      rpy: [0, 'pi/2', 0]
# over conveyor
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [1.21, 4.0, 1.624088]
      rpy: [0, 'pi/2', 0]
# over bins
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.748136, -1.377429, 0.982218]
      rpy: [0, 0.725374, 0]
