arm:
  type: ur10
sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [1.211507, 1.848453, 1.624088]
      rpy: [3.141593, 1.570417, 3.141593]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.748136, -1.377429, 0.982218]
      rpy: [0, 0.725374, 0]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.5]
      rpy: [0, 'pi/2', 0]

